CREATE TABLE IF NOT EXISTS GENERATION(
    GenerationID INTEGER PRIMARY KEY AUTOINCREMENT,
    Branch VARCHAR(16) NOT NULL,
    EngName VARCHAR(64) NOT NULL,
    JapName VARCHAR(64) NOT NULL,
    Overview TEXT NOT NULL,
    ImageLink VARCHAR(128) NOT NULL
)