CREATE TABLE IF NOT EXISTS HOLO(
    HoloID INTEGER PRIMARY KEY AUTOINCREMENT,
    EngName VARCHAR(64) NOT NULL,
    JapName VARCHAR(64) NOT NULL,
    BranchID VARCHAR(32) NOT NULL,
    GenerationID VARCHAR(64) NOT NULL,
    DebutDate Date NOT NULL,
    Height INTEGER NOT NULL,
    Birthday Date NOT NULL,
    Overview TEXT NOT NULL,
    Personality TEXT NOT NULL,
    ImageLink VARCHAR(128) NOT NULL,
    YoutubeLink VARCHAR(128) NOT NULL,
    TwitterLink VARCHAR(128) NOT NULL
    FOREIGN KEY(BranchID) REFERENCES BRANCH(BranchID),
    FOREIGN KEY(GenerationID) REFERENCES GENERATION(GenerationID)
)