CREATE TABLE IF NOT EXISTS BRANCH(
    BranchID INTEGER PRIMARY KEY AUTOINCREMENT,
    EngName VARCHAR(64) NOT NULL,
    JapName VARCHAR(64) NOT NULL,
    DebutDate Date NOT NULL,
    Overview TEXT NOT NULL,
    ImageLink VARCHAR(128) NOT NULL
)